In [207]:
import pandas as pd
import ast
import numpy as np
from collections import Counter

In [208]:
df = pd.read_csv("imdb_data (1).csv")

In [209]:
df

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,4/22/94,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It was supposed to be a routine prisoner trans...,Chasers,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687
2996,2997,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,tt2364975,sv,Vi är bäst!,Three girls in 1980s Stockholm decide to form ...,3.727996,...,3/28/13,102.0,"[{'iso_639_1': 'sv', 'name': 'svenska'}]",Released,NaN,We Are the Best!,"[{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...","[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de...",180590
2997,2998,NaN,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,10/11/96,120.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What's forgotten is not always gone.,The Long Kiss Goodnight,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761
2998,2999,NaN,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,1/16/04,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386
2999,3000,NaN,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,9/22/11,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They stole his life. He's taking it back.,Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155

In [210]:
df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

In [211]:
df.isnull().sum()

id                          0
belongs_to_collection    2396
budget                      0
genres                      7
homepage                 2054
imdb_id                     0
original_language           0
original_title              0
overview                    8
popularity                  0
poster_path                 1
production_companies      156
production_countries       55
release_date                0
runtime                     2
spoken_languages           20
status                      0
tagline                   597
title                       0
Keywords                  276
cast                       13
crew                       16
revenue                     0
dtype: int64

# Which movie made the highest profit? Who were its producer and director? Identify the actors in that film.

In [212]:
def extract_actors(x):
    actors = []
    try:
        data = ast.literal_eval(x)
        for i in data:
            actors.append(i.get('name'))
    except:
        pass
    return actors

df['actors'] = df['cast'].apply(extract_actors)

In [213]:
def extract_director(x):
    try:
        data = ast.literal_eval(x)
        for i in data:
            if i.get('job') == 'Director':
                return i.get('name')
    except:
        return None

df['director'] = df['crew'].apply(extract_director)

In [214]:
def extract_producers(x):
    producers = []
    try:
        data = ast.literal_eval(x)
        for i in data:
            if i.get('job') == 'Producer':
                producers.append(i.get('name'))
    except:
        pass
    return producers

df['producers'] = df['crew'].apply(extract_producers)

In [215]:
df['budget'] = pd.to_numeric(df['budget'], errors='coerce')
df['revenue'] = pd.to_numeric(df['revenue'], errors='coerce')

In [216]:
df = df[df['budget'] > 0]

In [217]:
df['profit'] = df['revenue'] - df['budget']
df['roi'] = (df['profit'] / df['budget']) * 100

df['roi'].replace([np.inf, -np.inf], np.nan, inplace=True)
df = df.dropna(subset=['roi'])

/tmp/ipykernel_17583/1194743756.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['profit'] = df['revenue'] - df['budget']
/tmp/ipykernel_17583/1194743756.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['roi'] = (df['profit'] / df['budget']) * 100
/tmp/ipykernel_17583/1194743756.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['roi'].replace([np.inf, -np.inf], np.nan, inplace=True)
/tmp/ipykernel_17583/1194743756.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['roi'].replace([np.inf, -np.inf], np.nan, inplace=True)

In [220]:
top_movie = df.loc[df['profit'].idxmax()]

print("\n Highest Profit Movie\n")
print("Movie:", top_movie['title'])
print("Profit:", top_movie['profit'])
print("Director:", top_movie['director'])
print("Actors:", top_movie['actors'])
print("Producers:", top_movie['producers'])

 Highest Profit Movie

Movie: Furious 7
Profit: 1316249360
Director: James Wan
Actors: ['Vin Diesel', 'Paul Walker', 'Dwayne Johnson', 'Michelle Rodriguez', 'Tyrese Gibson', 'Ludacris', 'Jordana Brewster', 'Djimon Hounsou', 'Tony Jaa', 'Ronda Rousey', 'Nathalie Emmanuel', 'Kurt Russell', 'Jason Statham', 'Sung Kang', 'Gal Gadot', 'Lucas Black', 'Elsa Pataky', 'Noel Gugliemi', 'John Brotherton', 'Luke Evans', 'Ali Fazal', 'Miller Kimsey', 'Charlie Kimsey', 'Eden Estrella', 'Gentry White', 'Iggy Azalea', 'Jon Lee Brody', 'Levy Tran', 'Anna Colwell', 'Viktor Hernandez', 'Steve Coulter', 'Robert Pralgo', 'Antwan Mills', 'J.J. Phillips', 'Jorge Ferragut', 'Sara Sohn', 'Benjamin Blankenship', 'D.J. Hapa', 'T-Pain', 'Brian Mahoney', 'Brittney Alger', 'Romeo Santos', 'Jocelin Donahue', 'Stephanie Langston', 'Jorge-Luis Pallo', 'Tego Calder√≥n', 'Nathalie Kelley', 'Shad Moss', 'Don Omar', 'Klement Tinaj', 'Caleb Walker', 'Cody Walker']
Producers: ['Vin Diesel', 'Neal H. Moritz', 'Michael Fottrell', 'Brandon Birtell']

# This data has information about movies made in different languages. Which language has the highest average ROI (return on investment)?

In [224]:

lang_roi = df.groupby('original_language')['roi'].mean().sort_values(ascending=False)

print("\n Top Language by ROI\n")
print(lang_roi.idxmax())

 Top Language by ROI

ko

# Find out the unique genres of movies in this dataset.

In [226]:
def extract_genres(x):
    genres = []
    try:
        data = ast.literal_eval(x)
        for i in data:
            genres.append(i.get('name'))
    except:
        pass
    return genres

df['genre_list'] = df['genres'].apply(extract_genres)

unique_genres = set()
for g in df['genre_list']:
    unique_genres.update(g)

print("Unique Genres\n")
print(unique_genres)

Unique Genres

{'Music', 'Drama', 'Fantasy', 'War', 'Animation', 'TV Movie', 'Action', 'Family', 'Western', 'History', 'Mystery', 'Romance', 'Adventure', 'Science Fiction', 'Crime', 'Thriller', 'Documentary', 'Horror', 'Foreign', 'Comedy'}

# Make a table of all the producers and directors of each movie. Find the top 3 producers who have produced movies with the highest average RoI?

In [228]:
df_exp = df.explode('producers')
df_exp = df_exp.dropna(subset=['producers'])

producer_roi = df_exp.groupby('producers')['roi'].mean()

top3_producers = producer_roi.sort_values(ascending=False).head(3)

top3_producers = top3_producers.reset_index()
top3_producers.columns = ['Producer', 'Average ROI']

print("Top 3 Producers by ROI\n")
print(top3_producers)

Top 3 Producers by ROI

       Producer  Average ROI
0  Ji Sang-yong  419747562.5
1    Lee Eun-ha  419747562.5
2      Jang Jin  419747562.5

In [229]:
table = df[['title', 'producers', 'director']]
print(table)

                                         title  \
0                       Hot Tub Time Machine 2
1     The Princess Diaries 2: Royal Engagement
2                                     Whiplash
3                                      Kahaani
5       Pinocchio and the Emperor of the Night
...                                        ...
2992                       The Thief of Bagdad
2993                              The Terminal
2997                   The Long Kiss Goodnight
2998                          Along Came Polly
2999                                 Abduction

                                              producers          director
0                                        [Andrew Panay]        Steve Pink
1     [Whitney Houston, Mario Iscovich, Debra Martin...    Garry Marshall
2     [David Lancaster, Michel Litvak, Jason Blum, H...   Damien Chazelle
3                                         [Sujoy Ghosh]       Sujoy Ghosh
5                                                    []    Hal Sutherland
...                                                 ...               ...
2992                                [Douglas Fairbanks]       Raoul Walsh
2993  [Steven Spielberg, Walter F. Parkes, Laurie Ma...  Steven Spielberg
2997  [Stephanie Austin, Shane Black, Renny Harlin, ...      Renny Harlin
2998      [Danny DeVito, Michael Shamberg, Stacey Sher]      John Hamburg
2999  [Doug Davison, Roy Lee, Ellen Goldsmith-Vein, ...    John Singleton

[2188 rows x 3 columns]

# Which actor has acted in the most number of movies? Deep dive into the movies, genres and profits corresponding to this actor.

In [234]:
actor_counter = Counter()

for actors in df['actors']:
    actor_counter.update(actors)

top_actor = actor_counter.most_common(1)[0][0]

print("Actor with Most Movies:")
print( top_actor)

actor_movies = df[df['actors'].apply(lambda x: top_actor in x)]

print("\nMovies of this actor:\n")
print(actor_movies[['title','profit']])

Actor with Most Movies:
Samuel L. Jackson

Movies of this actor:

                                             title      profit
29                                  Changing Lanes    49935764
47                               The Hateful Eight   111760117
642                              Coming to America   249752301
689   Star Wars: Episode III - Revenge of the Sith   737000000
1126                                  The Avengers  1299557910
1181                                        Jumper   137231186
1426                                         Shaft    61196498
1482                             Snakes on a Plane    29022014
1717                                       RoboCop   122688965
1735                                 Jurassic Park   857100000
1818  Star Wars: Episode II - Attack of the Clones   529398328
1861           Captain America: The Winter Soldier   544766572
1916                                  Jackie Brown    27673162
1970                                      Big Game    -1000000
2214                              Black Snake Moan    -4096154
2243                                   Sea of Love    91879513
2424                                 Deep Blue Sea    13648228
2544                                         Basic    -7207439
2739                               The Incredibles   539442092
2770                       Avengers: Age of Ultron  1125403694
2782                                  Out of Sight    29745568
2898                                 Patriot Games   133051587
2984                                      S.W.A.T.    36643346
2985                                   Freedomland   -23009372
2997                       The Long Kiss Goodnight    24456761

# Top 3 directors prefer which actors the most?

In [236]:
top_directors = df['director'].value_counts().head(3).index

print("Top Directors & Their Favorite Actors\n")

for director in top_directors:
    director_movies = df[df['director'] == director]
    actor_count = Counter()

    for actors in director_movies['actors']:
        actor_count.update(actors)

    print(f"\nDirector: {director}")
    print("Top Actors:", actor_count.most_common(3))

Top Directors & Their Favorite Actors


Director: Steven Spielberg
Top Actors: [('Harrison Ford', 3), ('Richard Dreyfuss', 2), ('Ted Grossman', 2)]

Director: Clint Eastwood
Top Actors: [('Clint Eastwood', 6), ('Clint Ward', 2), ('Sondra Locke', 2)]

Director: Steven Soderbergh
Top Actors: [('George Clooney', 3), ('Don Cheadle', 3), ('Luis Guzm√°n', 3)]